/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : ADC_1.c
**     Project     : SW0280006
**     Processor   : S32K144_100
**     Component   : adc_pal
**     Version     : Component SDK_S32K14x_09, Driver 01.00, CPU db: 3.00.000
**     Repository  : SDK_S32K14x_09
**     Compiler    : GNU C Compiler
**     Date/Time   : 2020-11-06, 11:18, # CodeGen: 29
**
**     Copyright 1997 - 2015 Freescale Semiconductor, Inc.
**     Copyright 2016-2017 NXP
**     All Rights Reserved.
**     
**     THIS SOFTWARE IS PROVIDED BY NXP "AS IS" AND ANY EXPRESSED OR
**     IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
**     OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
**     IN NO EVENT SHALL NXP OR ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
**     INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
**     SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
**     HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
**     STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
**     IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
**     THE POSSIBILITY OF SUCH DAMAGE.
** ###################################################################*/
/*!
** @file ADC_1.c
** @version 01.00
*/
/*!
**  @addtogroup ADC_1_module ADC_1 module documentation
**  @{
*/

/* MODULE ADC_1. */

/**
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 8.7, External variable could be made static.
 * The external variables will be used in other source files, with the same initialized values.
 */

#include <stddef.h>
#include "ADC_1.h"


/*! Configuration 0 declaration */

const adc_config_t ADC_1_InitConfig0 = {
    .sampleTicks        = 150,
    .numGroups          = 2,
    .groupConfigArray   = ADC_1_GroupArray0,
    .extension          = &ADC_1_Extension0
};

extension_adc_s32k1xx_t ADC_1_Extension0 = {
    .clockDivide              = ADC_CLK_DIVIDE_1,
    .resolution               = ADC_RESOLUTION_12BIT,
    .inputClock               = ADC_CLK_ALT_1,
    .voltageRef               = ADC_VOLTAGEREF_VREF,
    .supplyMonitoringEnable   = false
};

const adc_group_config_t ADC_1_GroupArray0[2u] = {
    /*        inputChannelArray,      resultBuffer,         numChannels,  numSetsResultBuffer,  hwTriggerSupport,  triggerSource,                   continuousConvEn,  callback,                callbackUserData */
    /* 0 */ { ADC_1_ChansArray00,  ADC_1_Results00,   5,            1,                    false,              TRGMUX_TRIG_SOURCE_DISABLED,     false,             ADC_callback,     ADC_1_Results00               },
    /* 1 */ { ADC_1_ChansArray01,  ADC_1_Results01,   4,            1,                    false,              TRGMUX_TRIG_SOURCE_DISABLED,     false,             ADC_callback,     ADC_1_Results01               },
};

adc_input_chan_t ADC_1_ChansArray00[5u] = {
    ADC_INPUTCHAN_EXT0,
    ADC_INPUTCHAN_EXT1,
    ADC_INPUTCHAN_EXT2,
    ADC_INPUTCHAN_EXT3,
    ADC_INPUTCHAN_EXT4,
};
uint16_t ADC_1_Results00[(5u) * (1u)];

adc_input_chan_t ADC_1_ChansArray01[4u] = {
    ADC_INPUTCHAN_EXT5,
    ADC_INPUTCHAN_EXT6,
    ADC_INPUTCHAN_EXT7,
    ADC_INPUTCHAN_EXT8,
};
uint16_t ADC_1_Results01[(4u) * (1u)];


/* END ADC_1. */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.1 [05.21]
**     for the Freescale S32K series of microcontrollers.
**
** ###################################################################
*/

