/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : memProtect1.c
**     Project     : SW0280006
**     Processor   : S32K144_100
**     Component   : mpu
**     Version     : Component SDK_S32K14x_09, Driver 01.00, CPU db: 3.00.000
**     Repository  : SDK_S32K14x_09
**     Compiler    : GNU C Compiler
**     Date/Time   : 2021-01-08, 15:12, # CodeGen: 49
**
**     Copyright 1997 - 2015 Freescale Semiconductor, Inc.
**     Copyright 2016-2017 NXP
**     All Rights Reserved.
**     
**     THIS SOFTWARE IS PROVIDED BY NXP "AS IS" AND ANY EXPRESSED OR
**     IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
**     OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
**     IN NO EVENT SHALL NXP OR ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
**     INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
**     SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
**     HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
**     STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
**     IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
**     THE POSSIBILITY OF SUCH DAMAGE.
** ###################################################################*/
/*!
** @file memProtect1.c
** @version 01.00
*/
/*!
**  @addtogroup memProtect1_module memProtect1 module documentation
**  @{
*/

/* MODULE memProtect1.
 *
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 8.7, External variable could be made static.
 * The external variable will be used in other source file that user initialize
 * to use this module.
 */

#include "memProtect1.h"

/*! Master access rights configuration 0 */
const mpu_master_access_right_t AccessRightConfig0[] =
{
    /*! CORE_0 */
    {
        .masterNum = FEATURE_MPU_MASTER_CORE,
        .accessRight = MPU_SUPERVISOR_RWX_USER_RWX,
        .processIdentifierEnable = false
    },
    /*! DEBUGGER_0 */
    {
        .masterNum = FEATURE_MPU_MASTER_DEBUGGER,
        .accessRight = MPU_SUPERVISOR_USER_RWX,
        .processIdentifierEnable = false
    },
    /*! DMA_0 */
    {
        .masterNum = FEATURE_MPU_MASTER_DMA,
        .accessRight = MPU_SUPERVISOR_RWX_USER_RWX,
        .processIdentifierEnable = false
    }
};
/*! Master access rights configuration 1 */
const mpu_master_access_right_t AccessReadOnly[] =
{
    /*! CORE_1 */
    {
        .masterNum = FEATURE_MPU_MASTER_CORE,
        .accessRight = MPU_SUPERVISOR_USER_R,
        .processIdentifierEnable = false
    },
    /*! DEBUGGER_1 */
    {
        .masterNum = FEATURE_MPU_MASTER_DEBUGGER,
        .accessRight = MPU_SUPERVISOR_RWX_USER_RWX,
        .processIdentifierEnable = false
    },
    /*! DMA_1 */
    {
        .masterNum = FEATURE_MPU_MASTER_DMA,
        .accessRight = MPU_SUPERVISOR_USER_NONE,
        .processIdentifierEnable = false
    }
};
/*! Master access rights configuration 2 */
const mpu_master_access_right_t AccessReadWrite[] =
{
    /*! CORE_2 */
    {
        .masterNum = FEATURE_MPU_MASTER_CORE,
        .accessRight = MPU_SUPERVISOR_USER_RW,
        .processIdentifierEnable = false
    },
    /*! DEBUGGER_2 */
    {
        .masterNum = FEATURE_MPU_MASTER_DEBUGGER,
        .accessRight = MPU_SUPERVISOR_RWX_USER_RWX,
        .processIdentifierEnable = false
    },
    /*! DMA_2 */
    {
        .masterNum = FEATURE_MPU_MASTER_DMA,
        .accessRight = MPU_SUPERVISOR_USER_NONE,
        .processIdentifierEnable = false
    }
};

/*! User configuration 0 */
const mpu_user_config_t memProtect1_UserConfig0[] =
{
    /*! Region number 0 */
    {
        .startAddr         = 0x00000000U,                       /*!< Memory region start address  */
        .endAddr           = 0xFFFFFFFFU,                       /*!< Memory region end address    */
        .masterAccRight    = AccessRightConfig0,                /*!< Master access right          */
        .processIdentifier = 0x00U,                             /*!< Process identifier           */
        .processIdMask     = 0x00U                              /*!< Process identifier mask      */
    },
    /*! Region number 1 */
    {
        .startAddr         = 0x14000000U,                       /*!< Memory region start address  */
        .endAddr           = 0x14000FFFU,                       /*!< Memory region end address    */
        .masterAccRight    = AccessReadOnly,                    /*!< Master access right          */
        .processIdentifier = 0x00U,                             /*!< Process identifier           */
        .processIdMask     = 0x00U                              /*!< Process identifier mask      */
    }
};
/* END memProtect1. */

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.1 [05.21]
**     for the Freescale S32K series of microcontrollers.
**
** ###################################################################
*/

